let stockProductos = [
    {id: 1, nombre: "Sabanas", medida: "King" , composicion: "100% algodón - 180 hilos", estilo: "lisas", precio: "4500", img: "../imagenes/cubrecama.jpg", cantidad: "1"}, 
    {id: 2, nombre: "Cubrecama", medida: "Queen" , composicion: "100% algodón - 180 hilos", estilo: "estampadas", precio: "4500", img: "../imagenes/cubrecama.jpg", cantidad: "1",}, 
    {id: 3, nombre: "Cubrecama", medida: "2 1/2p" , composicion: "100% algodón - 180 hilos", estilo: "lisas", precio: "4500", img: "../imagenes/cubrecama.jpg", cantidad: "1"}, 
    {id: 4, nombre: "Sabanas", medida: "1p" , composicion: "100% algodón - 200 hilos", estilo: "lisas", precio: "4500", img: "../imagenes/cubrecama.jpg", cantidad: "1"}, 
    {id: 5, nombre: "Sabanas", medida: "Twin" , composicion: "100% algodón - 200 hilos", estilo: "estampadas", precio: "4500", img: "../imagenes/cubrecama.jpg", cantidad: "1"}, 
    {id: 6, nombre: "Cubrecama", medida: "King" , composicion: "100% algodón - 200 hilos", estilo: "estampadass", precio: "4500", img: "../imagenes/cubrecama.jpg", cantidad: "1"}, 
    {id: 7, nombre: "Cubrecama", medida: "King" , composicion: "100% algodón - 200 hilos", estilo: "lisas", precio: "4500", img: "../imagenes/cubrecama.jpg", cantidad: "1"}, 
    {id: 8, nombre: "Sabanas", medida: "Queen" , composicion: "50% algodón 50% poliester", estilo: "estampadas", precio: "4500", img: "../imagenes/cubrecama.jpg", cantidad: "1"}, 
    {id: 9, nombre: "Sabanas", medida: "Queen" , composicion: "50% algodón 50% poliester", estilo: "estampadas", precio: "4500", img: "../imagenes/cubrecama.jpg", cantidad: "1"}, 
    {id: 10, nombre: "Cubrecama", medida: "Twin" , composicion: "50% algodón 50% poliester", estilo: "lisas", precio: "4500", img: "../imagenes/cubrecama.jpg", cantidad: "1"}, 
    {id: 11, nombre: "Sabanas", medida: "Twin" , composicion: "50% algodón 50% poliester", estilo: "lisas", precio: "4500", img: "../imagenes/cubrecama.jpg", cantidad: "1"}, 
    {id: 12, nombre: "Sabanas", medida: "Twin" , composicion: "50% algodón 50% poliester", estilo: "estampadas", precio: "4500", img: "../imagenes/cubrecama.jpg", cantidad: "1"}, 
    {id: 13, nombre: "Sabanas", medida: "2 1/2p" , composicion: "50% algodón 50% poliester", estilo: "estampadas", precio: "4500", img: "../imagenes/cubrecama.jpg", cantidad: "1"}, 
    {id: 14, nombre: "Sabanas", medida: "2 1/2p" , composicion: "50% algodón 50% poliester", estilo: "estampadas", precio: "4500", img: "../imagenes/cubrecama.jpg", cantidad: "1"}, 
    {id: 15, nombre: "Cubrecama", medida: "1p" , composicion: "50% algodón 50% poliester", estilo: "lisas", precio: "4500", img: "../imagenes/cubrecama.jpg", cantidad: "1"}, 
    {id: 16, nombre: "Sabanas", medida: "1p" , composicion: "50% algodón 50% poliester", estilo: "lisas", precio: "4500", img: "../imagenes/cubrecama.jpg", cantidad: "1"}, 
    {id: 17, nombre: "Sabanas", medida: "Queen" , composicion: "50% algodón 50% poliester", estilo: "lisas", precio: "4500", img: "../imagenes/cubrecama.jpg", cantidad: "1"},
]

